# Generated by Django 4.2.10 on 2024-03-02 05:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files/')),
            ],
        ),
    ]
